version: '3.4'
services:
  api:
    build:
      context: .
      target: runner
    volumes:
      - .:/go/src/github.com/liam-j-bennett/mather
    environment:
      - PORT=5000
      - API_KEY=some-api-key
    ports:
      - 5000:5000
    tty: true
